name: Playwright Visual Tests

on:
  push:
    branches: [main, prod]
  pull_request:
    branches: [main, prod]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.55.1-jammy
    env:
      MAIL_FROM: 'no-reply@notify.dev.alpha.gov.bb'
      SES_REGION: 'region'
      FEEDBACK_TO_EMAIL: 'no-reply@notify.dev.alpha.gov.bb'
      FEEDBACK_FROM_EMAIL: 'no-reply@notify.dev.alpha.gov.bb'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Run Playwright tests
        run: npx playwright test visual

      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 7