name: Playwright Tests

on:
  push:
    branches: [dev, prod]
  pull_request:
    branches: [dev, prod]
  workflow_dispatch:
    inputs:
      update_snapshots:
        description: 'Update visual regression baselines'
        required: false
        default: 'false'
        type: boolean

env:
  NODE_VERSION: '20'
  PLAYWRIGHT_BASE_URL: 'http://localhost:3000'

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps chromium
    
    - name: Build Next.js application
      run: npm run build

    - name: Check existing baselines
      run: |
        echo "=== Checking for existing baselines ==="
        if [ -d "tests/visual.spec.ts-snapshots" ]; then
          echo "Snapshots directory exists"
          find tests/visual.spec.ts-snapshots -name "*.png" | wc -l | xargs echo "Total snapshots:"
          find tests/visual.spec.ts-snapshots -name "*-chromium-linux.png" | head -5 | xargs -I {} echo "Found: {}"
        else
          echo "No snapshots directory found - this is the first run"
        fi

    - name: Run Playwright tests
      run: |
        if [ "${{ github.event.inputs.update_snapshots }}" == "true" ]; then
          echo "🔄 Updating snapshots..."
          npx playwright test visual.spec.ts --update-snapshots
        else
          echo "🧪 Running visual regression tests..."
          npx playwright test visual.spec.ts
        fi
      env:
        CI: true

    # Commit updated snapshots if this was a manual update
    - name: Commit updated snapshots
      if: github.event.inputs.update_snapshots == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add tests/**/*-snapshots/
        if git diff --staged --quiet; then
          echo "No snapshot changes to commit"
        else
          git commit -m "Update visual regression baselines"
          git push
        fi
    
    - name: Upload Playwright Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    
    - name: Upload visual diffs on failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: visual-diffs
        path: test-results/
        retention-days: 7

    - name: Comment on PR if visual tests failed
      if: failure() && github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const { owner, repo } = context.repo;
          const { number } = context.issue;
          
          await github.rest.issues.createComment({
            owner,
            repo,
            issue_number: number,
            body: `🔍 **Visual Regression Test Failed**
            
            Your changes have caused visual differences in the UI. Please review the differences in the [test artifacts](https://github.com/${owner}/${repo}/actions/runs/${{ github.run_id }}).
            
            **Next steps:**
            1. 📥 Download the \`visual-diffs\` artifact to see what changed
            2. 🔍 Review the diff images to confirm changes are intentional  
            3. ✅ If changes are correct, update baselines by running the workflow with "Update visual regression baselines" checked
            
            **Local commands:**
            \`\`\`bash
            # See the differences locally
            npx playwright test visual.spec.ts
            
            # Update baselines if changes are intentional
            npx playwright test visual.spec.ts --update-snapshots
            \`\`\`
            `
          });