name: Visual Comparison Tests

on:
  push:
    branches: [main, prod]
  pull_request:
    branches: [main, prod]
  workflow_dispatch:
    inputs:
      update_snapshots:
        description: 'Update visual regression baselines'
        required: false
        default: false
        type: boolean

env:
  NODE_VERSION: '20'
  PLAYWRIGHT_BASE_URL: 'http://localhost:3000'

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.55.0-noble
      options: --ipc=host --user 1001 --security-opt seccomp=unconfined
      
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    # No need to install Playwright browsers - they're already in the Docker image
    
    # ✅ Force install browsers inside the container
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Build Next.js application
      run: npm run build

    - name: Run Playwright tests
      run: |
        if [ "${{ github.event.inputs.update_snapshots }}" == "true" ]; then
          echo "🔄 Updating snapshots..."
          npx playwright test visual.spec.ts --update-snapshots
        else
          echo "🧪 Running visual regression tests..."
          npx playwright test visual.spec.ts
        fi
      env:
        CI: true
        HOME: /root

    - name: Commit updated snapshots
      if: github.event.inputs.update_snapshots == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add tests/**/*-snapshots/
        if git diff --staged --quiet; then
          echo "No snapshot changes to commit"
        else
          git commit -m "Update visual regression baselines [skip ci]"
          git push
        fi
    
    - name: Upload Playwright Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report-${{ github.run_id }}
        path: playwright-report/
        retention-days: 30
    
    - name: Upload visual diffs on failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: visual-diffs-${{ github.run_id }}
        path: test-results/
        retention-days: 7

    - name: Create check run for visual regression results
      if: always()
      uses: actions/github-script@v7
      with:
        script: |
          let conclusion = 'success';
          let summary = '✅ All visual regression tests passed!';
          
          if (process.env.JOB_STATUS === 'failure') {
            conclusion = 'failure';
            summary = `❌ Visual regression tests failed!
            
            📥 Download the artifacts to see visual differences:
            - **playwright-report-${{ github.run_id }}**: Full test report
            - **visual-diffs-${{ github.run_id }}**: Screenshots and diff images
            
            **To fix:**
            1. Review the diff images in artifacts
            2. If changes are intentional, run workflow with "Update visual regression baselines" checked
            3. Or run locally with Docker: \`npm run visual:update-docker\``;
          }
          
          console.log('Visual Regression Test Summary:');
          console.log(summary);
      env:
        JOB_STATUS: ${{ job.status }}